name: AuctionHouse
version: '1.0'
main: me.elaineqheart.auctionHouse.AuctionHouse
api-version: '1.21'
authors: [ ElaineQheart ]
website: https://www.youtube.com/@elaineqheart
softdepend: [ Vault ]
commands:
  ah:
    description: opens the auction house GUI
    permission: AuctionHouse.ah
    aliases: auctionhouse
  ahreload:
    description: reloads the yml files
    permission: AuctionHouse.ahreload
    aliases: auctionhousereload
permissions:
  AuctionHouse.ah:
    description: allows the player to use /ah
    default: true
  AuctionHouse.ahreload:
    description: allows the player to use /ahreload and reload the yml files
    default: op
